# Self-service golden-path starter-service generator.
from __future__ import annotations

import io
import re
import textwrap
import zipfile
from dataclasses import dataclass

import yaml


@dataclass(frozen=True)
class ServiceConfig:
    service_name: str
    team: str
    language: str = "Python"
    visibility: str = "internal"
    database: str = "None"
    environment: str = "development"
    slo_target: float = 99.9


def sanitize_service_name(value: str) -> str:
    cleaned = re.sub(r"[^a-z0-9-]+", "-", value.strip().lower().replace("_", "-"))
    cleaned = re.sub(r"-+", "-", cleaned).strip("-")
    if not cleaned:
        raise ValueError("Service name must contain at least one letter or number.")
    return cleaned[:63]


def _files(config: ServiceConfig) -> dict[str, str]:
    name = sanitize_service_name(config.service_name)
    team = config.team.strip() or "unassigned-team"
    db_note = config.database if config.database != "None" else "No database"

    catalog = {
        "apiVersion": "platformpulse.dev/v1",
        "kind": "Service",
        "metadata": {
            "name": name,
            "visibility": config.visibility,
            "owner": team,
        },
        "spec": {
            "language": config.language,
            "environment": config.environment,
            "database": config.database,
            "slo": {"availabilityTarget": float(config.slo_target)},
            "links": {
                "repository": f"https://github.com/example/{name}",
                "documentation": f"https://docs.example.internal/services/{name}",
                "runbook": f"https://runbooks.example.internal/{name}",
            },
        },
    }

    main_py = f'''# Generated FastAPI starter service for {name}.
from fastapi import FastAPI

app = FastAPI(title="{name}", version="0.1.0")


@app.get("/health")
def health() -> dict[str, str]:
    return {{"status": "ok", "service": "{name}"}}


@app.get("/")
def root() -> dict[str, str]:
    return {{"message": "Welcome to {name}", "owner": "{team}"}}
'''

    test_py = f'''from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def test_health() -> None:
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {{"status": "ok", "service": "{name}"}}
'''

    workflow = f'''name: {name} CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: python -m pytest -q
'''

    deployment = f'''apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: {name}
          image: ghcr.io/example/{name}:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
'''

    service = f'''apiVersion: v1
kind: Service
metadata:
  name: {name}
spec:
  selector:
    app: {name}
  ports:
    - port: 80
      targetPort: 8000
'''

    readme = f'''# {name}

Generated by PlatformPulse's self-service golden path.

## Ownership

- Team: **{team}**
- Visibility: **{config.visibility}**
- Environment: **{config.environment}**
- SLO target: **{float(config.slo_target)}%**
- Data dependency: **{db_note}**

## Run locally

```bash
python -m pip install -r requirements.txt
uvicorn app.main:app --reload
```

Open `http://localhost:8000/health`.

## Test

```bash
python -m pytest -q
```
'''

    return {
        f"{name}/app/__init__.py": "",
        f"{name}/app/main.py": main_py,
        f"{name}/tests/test_health.py": test_py,
        f"{name}/requirements.txt": (
            "fastapi==0.116.1\n"
            "uvicorn==0.35.0\n"
            "pytest==8.4.2\n"
            "httpx==0.28.1\n"
        ),
        f"{name}/Dockerfile": textwrap.dedent(
            '''\
            FROM python:3.11-slim
            WORKDIR /app
            COPY requirements.txt .
            RUN python -m pip install --no-cache-dir -r requirements.txt
            COPY . .
            EXPOSE 8000
            CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
            '''
        ),
        f"{name}/docker-compose.yml": (
            f'services:\n'
            f'  {name}:\n'
            f'    build: .\n'
            f'    ports:\n'
            f'      - "8000:8000"\n'
        ),
        f"{name}/.github/workflows/ci.yml": workflow,
        f"{name}/kubernetes/deployment.yaml": deployment,
        f"{name}/kubernetes/service.yaml": service,
        f"{name}/helm/Chart.yaml": (
            f"apiVersion: v2\n"
            f"name: {name}\n"
            f"description: Generated Helm chart for {name}\n"
            f"type: application\n"
            f"version: 0.1.0\n"
            f'appVersion: "0.1.0"\n'
        ),
        f"{name}/helm/values.yaml": (
            f"replicaCount: 2\n"
            f"image:\n"
            f"  repository: ghcr.io/example/{name}\n"
            f"  tag: latest\n"
            f"service:\n"
            f"  port: 80\n"
            f"slo:\n"
            f"  availabilityTarget: {float(config.slo_target)}\n"
            f'owner: "{team}"\n'
        ),
        f"{name}/service-catalog.yaml": yaml.safe_dump(catalog, sort_keys=False),
        f"{name}/README.md": readme,
        f"{name}/.gitignore": "__pycache__/\n.pytest_cache/\n.venv/\n",
    }


def generate_service_zip(config: ServiceConfig) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, content in _files(config).items():
            archive.writestr(path, content)
    buffer.seek(0)
    return buffer.getvalue()


def generated_paths(config: ServiceConfig) -> list[str]:
    return sorted(_files(config).keys())
