[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 10
fileWatcherType = "none"
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#155EEF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#172033"
font = "sans serif"
